apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  namespace: {{ .Release.Namespace }}
stringData:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ template "prometheus-operator.prometheus.fullname" (deepCopy . | mergeOverwrite (dict "Values" (dict "nameOverride" "prometheus-operator"))) }}.{{ .Release.Namespace }}.svc.cluster.local:9090
