apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  digitalocean_api_token: {{ .Values.digitalocean.apiToken | required "Missing required value digitalocean.apiToken (set one with --set 'digitalocean.apiToken=...')" | b64enc | quote }}
