apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-solver-dns
  namespace: {{ .Release.Namespace }}
data:
  access-token: {{ .Values.accessToken | b64enc | quote }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: {{ .Release.Name }}-staging
 namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-staging
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: {{ .Release.Name }}-solver-dns
            key: access-token
      selector:
        dnsZones: {{ .Values.dnsZones }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-prod
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-prod
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: {{ .Release.Name }}-solver-dns
            key: access-token
      selector:
        dnsZones: {{ .Values.dnsZones }}
