apiVersion: v1
kind: Secret
metadata:
  name: solver-dns
  namespace: cert-manager
data:
  access-token: {{ .Env.CERT_MANAGER_ACCESS_TOKEN_BASE64 }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
 namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Env.LETS_ENCRYPT_EMAIL }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: solver-dns
            key: access-token
      selector:
        dnsZones:
        - {{ .Env.CLUSTER_DOMAIN }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Env.LETS_ENCRYPT_EMAIL }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: solver-dns
            key: access-token
      selector:
        dnsZones:
        - {{ .Env.CLUSTER_DOMAIN }}
